# DISCLAIMER: I'm not a lawyer, I don't know if this is correct
accepted = [
    "OFL-1.1",
    "CC0-1.0",
    "Apache-2.0",
    "MIT",
    "Apache-2.0 WITH LLVM-exception",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "BSL-1.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "MPL-2.0",
    "ISC",
    "Zlib",
    "LicenseRef-UFL-1.0",
    "NCSA",
]

# otherwise it includes flits editor as GPL 3 only instead of GPL 3 and later
# instead we just use a seperate license file for ourselves
private = { ignore = true }